# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import os
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\HEMA DARSHINY\Downloads\installation_opencv-python\object_detection\build\assets\frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def navigate_to_objdection():
    objectdec_path = r"C:\Users\HEMA DARSHINY\Downloads\installation_opencv-python\object_detection\object.py"
    window.destroy()  # Close the current window
    os.system(f'python "{objectdec_path}"') 

def center_window(win, width, height):
    screen_width = win.winfo_screenwidth()
    screen_height = win.winfo_screenheight()
    x = (screen_width - width) // 2
    y = (screen_height - height) // 2
    win.geometry(f"{width}x{height}+{x}+{y}")

window = Tk()

window_width, window_height = 360, 640
center_window(window, window_width, window_height)
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 640,
    width = 362,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    360.0,
    640.0,
    fill="#FFF9F9",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=navigate_to_objdection,
    relief="flat"
)
button_1.place(
    x=40.0,
    y=186.0,
    width=280.0,
    height=273.0
)

canvas.create_rectangle(
    0.0,
    0.0,
    360.0,
    114.0,
    fill="#7CA5AE",
    outline="")

canvas.create_text(
    19.0,
    33.0,
    anchor="nw",
    text="Real time object detection",
    fill="#FFFFFF",
    font=("Amaranth Regular", 29 * -1)
)

canvas.create_rectangle(
    0.0,
    577.0,
    360.0,
    640.0,
    fill="#7CA5AE",
    outline="")

canvas.create_rectangle(
    155.0,
    541.0,
    212.0,
    590.0,
    fill="#7CA5AE",
    outline="")

canvas.create_text(
    140.0,
    592.0,
    anchor="nw",
    text="Object Detection",
    fill="#000000",
    font=("Amaranth Regular", 12 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=163.0,
    y=549.0,
    width=41.0,
    height=38.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=85.0,
    y=584.0,
    width=43.0,
    height=43.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=241.0,
    y=590.0,
    width=40.0,
    height=33.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=301.0,
    y=587.0,
    width=38.0,
    height=36.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=23.0,
    y=583.0,
    width=42.0,
    height=43.0
)
window.resizable(False, False)
window.mainloop()
