# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import os
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\HEMA DARSHINY\Downloads\installation_opencv-python\object_detection\build\assets\frame2")

selected_language = "en"

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def center_window(win, width, height):
    screen_width = win.winfo_screenwidth()
    screen_height = win.winfo_screenheight()
    x = (screen_width - width) // 2
    y = (screen_height - height) // 2
    win.geometry(f"{width}x{height}+{x}+{y}")

def navigate_to_camera():
    camera_path = r"C:\Users\HEMA DARSHINY\Downloads\installation_opencv-python\object_detection\camera.py"
    window.destroy() 
    os.environ["SELECTED_LANGUAGE"] = selected_language # Close the current window
    os.system(f'python "{camera_path}"') 
   
def select_language(language_code):
    global selected_language
    selected_language = language_code

window = Tk()

window_width, window_height = 360, 640
center_window(window, window_width, window_height)
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 640,
    width = 360,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    360.0,
    640.0,
    fill="#FFF9F9",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    360.0,
    114.0,
    fill="#7CA5AE",
    outline="")

canvas.create_text(
    32.0,
    66.0,
    anchor="nw",
    text="Language Learning",
    fill="#FFFFFF",
    font=("Amaranth Regular", 36 * -1)
)

canvas.create_text(
    17.0,
    258.0,
    anchor="nw",
    text="Choose Language desired  to Learn",
    fill="#000000",
    font=("Amaranth Regular", 20 * -1)
)

canvas.create_text(
    54.0,
    160.0,
    anchor="nw",
    text="Select language ",
    fill="#000000",
    font=("Amaranth Regular", 32 * -1)
)

button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
button_1 = Button(image=button_image_1, borderwidth=0, highlightthickness=0, command=lambda: [select_language("ms"), navigate_to_camera()], relief="flat")
button_1.place(x=16.0, y=369.0, width=326.0, height=55.0)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=13.0,
    y=320.0,
    width=329.0,
    height=53.59777069091797
)

button_image_3 = PhotoImage(file=relative_to_assets("button_3.png"))
button_3 = Button(image=button_image_3, borderwidth=0, highlightthickness=0, command=lambda: [select_language("zh-cn"), navigate_to_camera()], relief="flat")
button_3.place(x=16.0, y=419.0, width=326.0, height=55.0)

button_image_4 = PhotoImage(file=relative_to_assets("button_4.png"))
button_4 = Button(image=button_image_4, borderwidth=0, highlightthickness=0, command=lambda: [select_language("ta"), navigate_to_camera()], relief="flat")
button_4.place(x=16.0, y=468.0, width=326.0, height=55.0)

canvas.create_rectangle(
    0.0,
    577.0,
    360.0,
    640.0,
    fill="#7CA5AE",
    outline="")

canvas.create_rectangle(
    155.0,
    541.0,
    212.0,
    590.0,
    fill="#7CA5AE",
    outline="")

canvas.create_text(
    140.0,
    592.0,
    anchor="nw",
    text="Select language",
    fill="#000000",
    font=("Amaranth Regular", 12 * -1)
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=85.0,
    y=590.0,
    width=41.0,
    height=38.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=162.0,
    y=549.0,
    width=43.0,
    height=43.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=241.0,
    y=590.0,
    width=40.0,
    height=33.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=301.0,
    y=587.0,
    width=38.0,
    height=36.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=23.0,
    y=583.0,
    width=42.0,
    height=43.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=129.0,
    y=0.0,
    width=95.0,
    height=77.0
)
window.resizable(False, False)
window.mainloop()
